### ISSUE TITLE
Y grid line not displayed when no sufficient Y value

### ISSUE THREAD

**Issue by patrickkusebauch** [sbeyn/kibana-plugin-line-sg#2]
Hello,
I have a problem with displaying the Y grid line.

I use this grid line to display a "goal" to reach within a period of time (time on X axis). 
What I would like for the goal line is to be always displayed, regardless of the data.
At the same time, if the data surpasses the goal line, I also want all the surpassing data displayed.

Currently I have the following issue:

1) If I just set the grid line and input the data, if the data doesn't reach the goal, the Y axis is scaled by the data and will not show the grid line.

2) If I set the Y.max to be higher than the goal grid (to ensure the grid line is displayed) and the data surpasses this Y.max, the surpassing data will not be displayed. 

I believe in case 1) the Y axes should be, or have option to, be scaled to always include the grid line.

**Comment by sbeyn** [comment]
hi I just make changes by adding an autoscale on Y and Y2 axes. I think it can solve the case 2).
I will add in the coming days Y grid in the conditions of the autoscale ...
